//! The placeholder ship: a procedural mesh, without an asset.
//!
//! The "ship in the scene" stage stands on three oracles -- `near` arriving from
//! `Scene`, the number of depth passes, and the camera -- and **the hull's shape
//! enters none of them**. So the geometry here is generated by code.
//!
//! Since T5d3 the frame also has a cooked hull from Blender
//! (`Frame::load_ship`), but this mesh has not gone anywhere and **remains a
//! working fixture**: it has an analytic volume ([`volume_m3`]), which the
//! imported model does not have at all. The frame draws it when the asset is
//! not on disk either -- `/assets/` is not in git.
//!
//! WARNING: **the shape is deliberately asymmetric, and that is not
//! decoration.** A ball would be cheaper, but the rotation of a smooth sphere
//! cannot be shown at all -- the silhouette and the normal map onto themselves
//! (R1). The third-person camera watches exactly the orientation, so a fixture
//! whose orientation is invisible would hide a bug the same way a camera above
//! the centre of a cube face hid D13 and D14. The nose distinguishes the axis
//! direction, the fins a plane, the porthole roll: four fins on their own leave
//! a 90-degree symmetry, and it is the porthole that breaks it.
//!
//! Axes: the ship's nose points along `+Z`, and the origin is halfway between
//! tail and nose.

use crate::sphere::Mesh;

/// Height of the placeholder ship, metres. A few metres is the scale at which
/// `near` from `Scene` matters for the first time: the altitude above the body
/// divided by ten would clip the hull entirely.
pub const DEFAULT_HEIGHT_M: f64 = 6.0;

/// The hull's largest radius, as a fraction of the height.
const RADIUS_FRACTION: f64 = 0.2;

/// How many facets the hull's circle has. Both the mesh and the analytic volume
/// depend on it: a polygon has area `(n/2)*sin(2pi/n)*r^2`, not `pi*r^2`, and
/// the oracle below compares against the first -- that is exactly, rather than
/// with a tolerance for mesh coarseness.
const SEGMENTS: u32 = 32;

/// How many facets the porthole's circle has.
const PORTHOLE_SEGMENTS: u32 = 12;

const FINS: u32 = 4;

/// The hull profile from tail to nose: (fraction of height, fraction of the
/// largest radius). Vertical sections (equal `z`) are rings: the nozzle collar
/// near the tail and the ledge under the nose cone.
const PROFILE: [[f64; 2]; 14] = [
    [0.000, 0.000],
    [0.000, 0.260],
    [0.045, 0.260],
    [0.060, 0.330],
    [0.120, 0.520],
    [0.250, 0.760],
    [0.400, 0.930],
    [0.520, 1.000],
    [0.640, 0.960],
    [0.720, 0.860],
    [0.760, 0.800],
    [0.775, 0.800],
    [0.790, 0.760],
    [1.000, 0.000],
];

/// The fin triangle in the (radius, height) plane, in fractions of `r_max` and
/// of the height: the root inside the hull, the tip outward and slightly below
/// the tail.
const FIN_PROFILE: [[f64; 2]; 3] = [[0.40, 0.300], [0.40, 0.020], [1.90, 0.000]];

/// Fin thickness, as a fraction of the largest radius.
const FIN_THICKNESS: f64 = 0.10;

/// The porthole: height, the inner and outer radii of its axis and its own
/// radius -- all in the same fractions. The outer end sticks out past the hull
/// outline (which is ~0.967 there), otherwise the ring would not be visible from
/// the side.
const PORTHOLE_Z: f64 = 0.620;
const PORTHOLE_INNER: f64 = 0.900;
const PORTHOLE_OUTER: f64 = 1.120;
const PORTHOLE_RADIUS: f64 = 0.220;

/// The ship mesh: the hull by revolving the profile, four fins and a porthole.
/// The components are **not stitched** to each other -- each is a closed shell
/// on its own, which is why the signed volume of the whole mesh equals the sum
/// of their volumes even where they intersect.
///
/// Hull roughness in the engine's and the game's fixtures.
///
/// Not a measured quantity but a choice of look: 0.40 is enamel, whose
/// highlight is no longer a mirror but not yet a matte blob. This constant
/// exists precisely so that probes and tests do not spread the hull across ten
/// different materials.
pub const HULL_ROUGHNESS: f32 = 0.40;

/// The hull is **painted**, that is a dielectric: zero, not one (T9b).
///
/// Before T9 the hull was metal, and that was honest while it was a bare hull
/// of one colour. The reference model is painted with enamel, and paint is a
/// dielectric over metal: it does have diffuse reflection, and that is what
/// carries the colour. With `metallic = 1` the base colour would become `F0`,
/// that is a tint of the highlight itself, and white enamel would look like
/// dark chrome -- exactly how it looked in the first T9a frame.
///
/// Intermediate values do not exist physically, so zero rather than 0.1 "to
/// make it more interesting": a material either has free electrons or it does
/// not.
pub const HULL_METALLIC: f32 = 0.0;

pub fn generate(height_m: f64) -> Mesh {
    let mut mesh = Mesh {
        positions: Vec::new(),
        normals: Vec::new(),
        indices: Vec::new(),
    };

    hull(height_m, &mut mesh);
    for k in 0..FINS {
        let angle = 2.0 * std::f64::consts::PI * f64::from(k) / f64::from(FINS);
        fin(height_m, angle, &mut mesh);
    }
    porthole(height_m, &mut mesh);

    mesh
}

/// The volume the mesh must enclose -- the sum of all five shells' volumes.
/// Computed from the same tables as the geometry but by **a different route**:
/// truncated cones instead of triangles. That is the step's oracle.
pub fn volume_m3(height_m: f64) -> f64 {
    let r_max = height_m * RADIUS_FRACTION;

    let ring = ring_area(SEGMENTS);
    let mut hull = 0.0;
    for pair in PROFILE.windows(2) {
        let (z0, r0) = (pair[0][0] * height_m, pair[0][1] * r_max);
        let (z1, r1) = (pair[1][0] * height_m, pair[1][1] * r_max);
        hull += (z1 - z0) * (r0 * r0 + r0 * r1 + r1 * r1) / 3.0;
    }
    hull *= ring;

    let a = FIN_PROFILE[0];
    let b = FIN_PROFILE[1];
    let c = FIN_PROFILE[2];
    let area = 0.5
        * ((b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])).abs()
        * r_max
        * height_m;
    let fins = f64::from(FINS) * area * FIN_THICKNESS * r_max;

    let porthole = ring_area(PORTHOLE_SEGMENTS)
        * (PORTHOLE_RADIUS * r_max).powi(2)
        * (PORTHOLE_OUTER - PORTHOLE_INNER)
        * r_max;

    hull + fins + porthole
}

/// The area of a regular `n`-gon inscribed in a unit circle. For infinite `n`
/// that is pi; a mesh of `n` facets encloses exactly this much.
fn ring_area(segments: u32) -> f64 {
    let n = f64::from(segments);
    0.5 * n * (2.0 * std::f64::consts::PI / n).sin()
}

/// The hull: the profile revolved about the `Z` axis. The normal at a profile
/// node is the mean of the neighbouring segments' normals, computed **in
/// metres**: `z` and `r` scale differently, so in fractions the slope would be
/// wrong.
fn hull(height_m: f64, mesh: &mut Mesh) {
    let r_max = height_m * RADIUS_FRACTION;
    let base = mesh.positions.len() as u32;

    for (i, point) in PROFILE.iter().enumerate() {
        let z = (point[0] - 0.5) * height_m;
        let r = point[1] * r_max;
        let (n_r, n_z) = profile_normal(i, height_m, r_max);

        for j in 0..=SEGMENTS {
            let phi = 2.0 * std::f64::consts::PI * f64::from(j) / f64::from(SEGMENTS);
            let (sin_phi, cos_phi) = phi.sin_cos();

            mesh.positions.push([r * cos_phi, r * sin_phi, z]);
            mesh.normals
                .push([(n_r * cos_phi) as f32, (n_r * sin_phi) as f32, n_z as f32]);
        }
    }

    // +1, because the seam closes by repeating a vertex rather than by a
    // wrapping index -- the same as in `sphere::generate`.
    let stride = SEGMENTS + 1;
    for i in 0..(PROFILE.len() as u32 - 1) {
        for j in 0..SEGMENTS {
            let a = base + i * stride + j;
            let b = a + stride;

            mesh.indices.push(a);
            mesh.indices.push(a + 1);
            mesh.indices.push(b);

            mesh.indices.push(a + 1);
            mesh.indices.push(b + 1);
            mesh.indices.push(b);
        }
    }
}

/// The normal at a profile node, in the (radius, axis) plane. For a segment
/// with increments `dz` and `dr` the outward normal is `(dz, -dr)`: on a
/// vertical ring (`dz = 0`) it becomes pure `-+Z`, that is the ring faces along
/// the axis, as it should.
fn profile_normal(i: usize, height_m: f64, r_max: f64) -> (f64, f64) {
    let segment = |a: usize, b: usize| {
        let dz = (PROFILE[b][0] - PROFILE[a][0]) * height_m;
        let dr = (PROFILE[b][1] - PROFILE[a][1]) * r_max;
        let length = (dz * dz + dr * dr).sqrt();
        (dz / length, -dr / length)
    };

    let (mut n_r, mut n_z) = (0.0, 0.0);
    if i > 0 {
        let (r, z) = segment(i - 1, i);
        n_r += r;
        n_z += z;
    }
    if i + 1 < PROFILE.len() {
        let (r, z) = segment(i, i + 1);
        n_r += r;
        n_z += z;
    }

    let length = (n_r * n_r + n_z * n_z).sqrt();
    (n_r / length, n_z / length)
}

/// A fin: a triangular prism rotated by `angle` about the axis. The faces are
/// flat, so they have vertices of their own -- an averaged normal on a thin
/// wedge would come out nearly zero.
fn fin(height_m: f64, angle: f64, mesh: &mut Mesh) {
    let r_max = height_m * RADIUS_FRACTION;
    let half = 0.5 * FIN_THICKNESS * r_max;
    let (sin_a, cos_a) = angle.sin_cos();

    let corner = |k: usize, side: f64| {
        let r = FIN_PROFILE[k][0] * r_max;
        let z = (FIN_PROFILE[k][1] - 0.5) * height_m;
        [
            r * cos_a - side * half * sin_a,
            r * sin_a + side * half * cos_a,
            z,
        ]
    };

    let plus: Vec<[f64; 3]> = (0..3).map(|k| corner(k, 1.0)).collect();
    let minus: Vec<[f64; 3]> = (0..3).map(|k| corner(k, -1.0)).collect();

    // The end caps. Winding A->B->C in the (radius, axis) plane gives a normal
    // against the tangent, so the "+" side closes in reverse order.
    push_triangle(mesh, plus[0], plus[2], plus[1]);
    push_triangle(mesh, minus[0], minus[1], minus[2]);

    for k in 0..3 {
        let n = (k + 1) % 3;
        push_triangle(mesh, plus[k], plus[n], minus[n]);
        push_triangle(mesh, plus[k], minus[n], minus[k]);
    }
}

/// The porthole: a short cylinder across the hull, capped at both ends. It is
/// the only one on the ship, so it is what breaks the 90-degree symmetry the
/// four fins leave behind.
fn porthole(height_m: f64, mesh: &mut Mesh) {
    let r_max = height_m * RADIUS_FRACTION;
    let radius = PORTHOLE_RADIUS * r_max;
    let z = (PORTHOLE_Z - 0.5) * height_m;
    let inner = PORTHOLE_INNER * r_max;
    let outer = PORTHOLE_OUTER * r_max;

    let rim = |x: f64, k: u32| {
        let alpha = 2.0 * std::f64::consts::PI * f64::from(k) / f64::from(PORTHOLE_SEGMENTS);
        let (sin_alpha, cos_alpha) = alpha.sin_cos();
        [x, radius * cos_alpha, z + radius * sin_alpha]
    };

    let centre_inner = [inner, 0.0, z];
    let centre_outer = [outer, 0.0, z];

    for k in 0..PORTHOLE_SEGMENTS {
        let n = (k + 1) % PORTHOLE_SEGMENTS;

        push_triangle(mesh, rim(inner, k), rim(outer, n), rim(outer, k));
        push_triangle(mesh, rim(inner, k), rim(inner, n), rim(outer, n));

        push_triangle(mesh, centre_outer, rim(outer, k), rim(outer, n));
        push_triangle(mesh, centre_inner, rim(inner, n), rim(inner, k));
    }
}

/// A flat triangle: three vertices of its own with the face's normal.
fn push_triangle(mesh: &mut Mesh, a: [f64; 3], b: [f64; 3], c: [f64; 3]) {
    let u = [b[0] - a[0], b[1] - a[1], b[2] - a[2]];
    let v = [c[0] - a[0], c[1] - a[1], c[2] - a[2]];
    let n = [
        u[1] * v[2] - u[2] * v[1],
        u[2] * v[0] - u[0] * v[2],
        u[0] * v[1] - u[1] * v[0],
    ];
    let length = (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt();
    let normal = [
        (n[0] / length) as f32,
        (n[1] / length) as f32,
        (n[2] / length) as f32,
    ];

    let base = mesh.positions.len() as u32;
    for p in [a, b, c] {
        mesh.positions.push(p);
        mesh.normals.push(normal);
    }
    mesh.indices.push(base);
    mesh.indices.push(base + 1);
    mesh.indices.push(base + 2);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sphere;

    /// The signed volume of a closed shell by the divergence theorem. Positive
    /// means outward winding; the sum over components is additive even when they
    /// intersect, because each shell is integrated on its own.
    fn signed_volume(mesh: &Mesh) -> f64 {
        let mut total = 0.0;
        for t in mesh.indices.chunks(3) {
            let a = mesh.positions[t[0] as usize];
            let b = mesh.positions[t[1] as usize];
            let c = mesh.positions[t[2] as usize];
            total += a[0] * (b[1] * c[2] - b[2] * c[1]) - a[1] * (b[0] * c[2] - b[2] * c[0])
                + a[2] * (b[0] * c[1] - b[1] * c[0]);
        }
        total / 6.0
    }

    /// The largest distance from a rotated vertex to the nearest original one,
    /// both ways. Zero means the rotation maps the mesh onto itself.
    fn misfit(mesh: &Mesh, turn: fn([f64; 3]) -> [f64; 3]) -> f64 {
        let turned: Vec<[f64; 3]> = mesh.positions.iter().map(|p| turn(*p)).collect();
        let nearest = |p: [f64; 3], set: &[[f64; 3]]| {
            set.iter()
                .map(|q| {
                    let d = [p[0] - q[0], p[1] - q[1], p[2] - q[2]];
                    (d[0] * d[0] + d[1] * d[1] + d[2] * d[2]).sqrt()
                })
                .fold(f64::INFINITY, f64::min)
        };

        let there = turned
            .iter()
            .map(|p| nearest(*p, &mesh.positions))
            .fold(0.0, f64::max);
        let back = mesh
            .positions
            .iter()
            .map(|p| nearest(*p, &turned))
            .fold(0.0, f64::max);
        there.max(back)
    }

    fn roll_90(p: [f64; 3]) -> [f64; 3] {
        [-p[1], p[0], p[2]]
    }
    fn roll_180(p: [f64; 3]) -> [f64; 3] {
        [-p[0], -p[1], p[2]]
    }
    fn end_over_end(p: [f64; 3]) -> [f64; 3] {
        [p[0], -p[1], -p[2]]
    }

    #[test]
    fn the_shells_enclose_exactly_the_volume_the_tables_say() {
        let mesh = generate(DEFAULT_HEIGHT_M);
        let measured = signed_volume(&mesh);
        let expected = volume_m3(DEFAULT_HEIGHT_M);

        // A positive sign means all five shells wind outward; matching the
        // number means they are also closed: a hole or a flipped triangle would
        // shift the sum.
        assert!(
            (measured - expected).abs() < 1.0e-12 * expected,
            "the mesh encloses {measured} m3, while the tables say {expected}"
        );
    }

    #[test]
    fn the_volume_grows_with_the_cube_of_the_height() {
        let one = volume_m3(1.0);
        let two = volume_m3(2.0);
        assert!(
            (two - 8.0 * one).abs() < 1.0e-12 * two,
            "{two} against {} -- the shape depends on the height",
            8.0 * one
        );
    }

    #[test]
    fn no_turn_but_the_identity_leaves_the_ship_where_it_was() {
        let ship = generate(DEFAULT_HEIGHT_M);

        // A 90-degree roll maps the fins onto themselves -- only the porthole
        // is left, and it is what must catch this.
        let roll = misfit(&ship, roll_90);
        assert!(
            roll > 0.1,
            "a 90-degree roll leaves the ship where it was: {roll} m"
        );
        assert!(misfit(&ship, roll_180) > 0.1);
        assert!(misfit(&ship, end_over_end) > 1.0);

        // Control: the same check is silent on a ball -- which is exactly why a
        // ball cannot be a fixture for orientation.
        let ball = sphere::generate(0.5 * DEFAULT_HEIGHT_M, 16, SEGMENTS);
        assert!(
            misfit(&ball, roll_90) < 1.0e-9,
            "the ball is suddenly asymmetric -- the check measures the wrong thing"
        );
    }

    #[test]
    fn every_index_is_in_range() {
        let mesh = generate(DEFAULT_HEIGHT_M);
        let count = mesh.positions.len() as u32;
        assert_eq!(mesh.indices.len() % 3, 0);
        for &i in &mesh.indices {
            assert!(i < count, "index {i} is out of range for {count} vertices");
        }
    }
}
